# Generated by Django 5.2.1 on 2025-10-27 21:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner'),
        ),
    ]
