# Generated by Django 5.2.3 on 2025-06-11 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmanager',
            name='promoter',
            field=models.ForeignKey(limit_choices_to={'role': 'promoter'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'artist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artistmanager',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='artists.artistprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='artistmanager',
            unique_together={('artist', 'promoter')},
        ),
    ]
