# Generated by Django 5.2.3 on 2025-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='verification_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
