# Generated by Django 5.2.3 on 2025-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artistprofile_email_artistprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active')], default='invited', max_length=20),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='name',
            field=models.CharField(default='Unknown', max_length=255, unique=True),
        ),
    ]
