# Generated by Django 5.2.1 on 2025-10-28 00:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artistprofile_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
